version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    volumes:
      - backend-data:/app/data
    environment:
      - SERVICE_NAME=BackendService
    networks:
      - app-network

  frontend:
    build: ./frontend
    logging:
      driver: syslog
      options:
        syslog-address: "tcp://localhost:5001"
        tag: "myapp-container"
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:5000
    networks:
      - app-network

volumes:
  backend-data:

networks:
  app-network:
    driver: bridge
