Vagrant.configure("2") do |config|
    config.vm.synced_folder "./examples", "/home/vagrant/examples"
    config.vm.define "docker" do |docker|
      docker.vm.box = "generic/ubuntu2204"
      docker.vm.hostname = "docker"
      
      docker.vm.provider "virtualbox" do |vb|
        vb.name = "docker-vm"
        vb.memory = "2048"
        vb.cpus = 2
      end
  
      docker.vm.network "private_network", ip: "192.168.56.112"
    end
  end