version: '3.8'
services:
  web:
    build: ./web
    ports:
      - "8000:8000"
    volumes:
      - ./web:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
